enum {
	BROADCAST_TYPE_DISCOVER,
	BROADCAST_TYPE_CONFIG,
	BROADCAST_TYPE_SIGNALLOST,
};

enum {
	BROADCAST_CONFIG_INSTANT,
	BROADCAST_CONFIG_AGGREGATE,
	BROADCAST_CONFIG_PERIODIC,
	BROADCAST_CONFIG_ONCHANGE,
};

struct broadcast_msg {
	uint8_t type;
	int16_t info;
};

